### PR TITLE
Okhttp integration

### PR DESCRIPTION
**Pull request by Maragues**
Use OkHttp if it's loaded.

This should fix issue #32

### CODE REVIEW

**Comment by wymore** [comment]
Thank you very much!:£©

**Comment by Maragues** [comment]
Sorry for the mess. I just reset my master to yours, hopefully that should fix it for future pull requests. Still learning git stuff..

**Comment by Maragues** [comment]
I just stomped on this OkHttp bug https://github.com/square/okhttp/issues/184 It crashes other ssl requests if you don't hack a workaround everytime you invoke OkHttp. They won't fix it until 2.0 comes out, this is a solution until then.

**Comment by foxykeep** [comment]
Going to have to do some code cleanup but I'll do in a commit after I merge your branch. so let's merge :)

**Comment by foxykeep** [comment]
Just pushed the changes for the code cleanup. Tell me if you see some issues with it.

**Comment by LOG-TAG** [comment]
it would be better if we get volley with okhttp  for DataDroid ! I think that is in the To Do list of foxykeep ! Source: https://plus.google.com/114592751246503219483/posts/QdA2DkVgbHT (see the last comment)

**Comment by foxykeep** [comment]
Main problem is that the project is currently in limbo from my point of view. I dont have time to work on it anymore. And I dont even use it anymore in any of my apps ... :/ (They dont need webservices)

**Pull request merged**
